"""initial migration

Revision ID: 3b316793e520
Revises: 
Create Date: 2025-05-20 14:03:21.755560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b316793e520'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expression', sa.String(), nullable=False),
    sa.Column('variable', sa.String(), nullable=False),
    sa.Column('lower_limit', sa.String(), nullable=True),
    sa.Column('upper_limit', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_histories_id'), 'histories', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_histories_id'), table_name='histories')
    op.drop_table('histories')
    # ### end Alembic commands ###
